# Generated by Django 4.1.7 on 2023-03-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='периодичность выполнения привычки'),
        ),
    ]
